---
- name: Install required packages
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - galera-4
      - rsync
      - python3
      - python3-pip
      - pkg-config 
      - libmysqlclient-dev  
    state: present

- name: Install python3-mysqlclient
  pip:
    name: mysqlclient

- name: Stop MariaDB Service on All Nodes
  service:
    name: mariadb
    state: stopped

- name: Setup MariaDB configuration for Galera Cluster
  template:
    src: galera.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/60-galera.cnf

- name: bootstap cluster
  import_tasks: bootstrap.yml

- name: Check for Galera Cluster Status
  import_tasks: check.yml

- name: Create MySQL User
  import_tasks: users.yml