- name: Try change MySQL root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ db_root_password }}"
    update_password: always
    state: present
  ignore_errors: true
  run_once: true
  delegate_to: "{{ groups['galera_cluster'][0] }}"

- name: Create MySQL user for application
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: '%'
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
  run_once: true
  delegate_to: "{{ groups['galera_cluster'][0] }}"

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
  run_once: true
  delegate_to: "{{ groups['galera_cluster'][0] }}"