---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install HAProxy
  apt:
    name: haproxy
    state: present

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Ensure HAProxy is started and enabled
  service:
    name: haproxy
    state: started
    enabled: true