---
- name: Install PHP and required PHP extensions
  apt:
    name:
      - php8.1
      - php8.1-fpm
      - php8.1-mysql
      - php8.1-xml
      - php8.1-mbstring
      - php8.1-curl
      - php8.1-zip
      - php8.1-gd
      - php8.1-bcmath
      - php8.1-cli  # Menambahkan php-cli untuk Composer
    state: present
    update_cache: yes

- name: Ensure PHP-FPM is running and enabled
  systemd:
    name: php8.1-fpm
    state: started
    enabled: yes

- name: Copy PHP configuration for Laravel
  template:
    src: php.ini
    dest: /etc/php/8.1/fpm/php.ini
  notify: Restart PHP-FPM

- name: Ensure PHP-FPM is running and enabled
  systemd:
    name: php8.1-fpm
    state: restarted
    enabled: yes
