- name: Update and upgrade all servers
  hosts: all
  become: true
  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes
    
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist

- name: Configure Galera Cluster and HAProxy
  hosts: galera_cluster
  become: true
  roles:
    - galera
  handlers:
    - name: Restart MariaDB
      service:
        name: mysql
        state: restarted