---
- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Install Composer
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

- name: Remove Composer installer
  file:
    path: /tmp/composer-setup.php
    state: absent

# - name: Verify Composer installation
#   command: composer --version
#   register: composer_version

# - name: Display Composer version
#   debug:
#     msg: "Composer version: {{ composer_version.stdout }}"
